# Generated by Django 3.0.5 on 2020-05-14 08:02

from django.db import migrations, models
import profilewallet.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet_id', models.CharField(db_index=True, default=profilewallet.models.get_uuid4, editable=False, max_length=36, unique=True)),
                ('first_name', models.CharField(help_text='Card owner first name', max_length=30, verbose_name='First name')),
                ('last_name', models.CharField(help_text='Card owner last name', max_length=30, verbose_name='Last name')),
                ('card_number', models.CharField(max_length=20, verbose_name='Card number')),
                ('card_type', models.CharField(choices=[('CB', 'Carte Bleu / VISA / Mastercard'), ('AMEX', 'American Express')], max_length=20, verbose_name='Card type')),
                ('card_expiry', models.CharField(help_text='Format: MMYY (eg 0213 for february 2013)', max_length=4, verbose_name='Card expiry')),
            ],
            options={
                'verbose_name': 'wallet',
                'verbose_name_plural': 'wallets',
            },
        ),
    ]
