# Generated by Django 3.0.5 on 2020-05-14 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profilewallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
